apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  labels:
    app: hello-world-label
spec: 
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: hello-world-label
